//go:build js || wasm

package main

// Component TypeIDs - generated by compiler.
// These constants uniquely identify each component type for router pivot algorithm.
const (
	// Layouts
	MainLayout_TypeID  uint32 = 0x8F22A1BC
	AdminLayout_TypeID uint32 = 0x7E11B2AD

	// Pages
	HomePage_TypeID     uint32 = 0x6C00C9FE
	AboutPage_TypeID    uint32 = 0x5D11D8CF
	AdminPage_TypeID    uint32 = 0x4E22E7B0
	SettingsPage_TypeID uint32 = 0x3F33F681
	UsersPage_TypeID    uint32 = 0x1D55E483
	BlogPage_TypeID     uint32 = 0x2E44F592
	PageNotFound_TypeID uint32 = 0x1F55E483

	// Shared components
	RouterLink_TypeID uint32 = 0x00666D374
)
